#!/bin/sh
#
# /etc/rc.d/motion: start/stop motion daemon
#

PIDFILE=/var/run/motion/motion.pid

case $1 in
start)
	sudo -u motion /usr/bin/motion -c /etc/motion/motion.conf -p $PIDFILE
	;;
stop)
	kill $(cat $PIDFILE)
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
reload)
	kill -HUP $(cat $PIDFILE)
	;;
*)
	echo "usage: $0 [start|stop|restart|reload]"
	;;
esac

# End of file
