#!/bin/sh
#
# /etc/rc.d/ezstream: start/stop ezstream daemon
#

case $1 in
start)
	ezstream -q -c /etc/ezstream.conf &
	;;
stop)
	kill -s KILL $(pidof ezstream)
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
