#!/bin/sh
#
# /etc/rc.d/igmpproxy: start/stop igmpproxy daemon
#

case $1 in
start)
	/usr/sbin/igmpproxy /etc/igmpproxy.conf &
	;;
stop)
	killall -q /usr/sbin/igmpproxy
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
