#!/bin/sh
#
# /etc/rc.d/acpid: start/stop ACPI daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/acpid
PID=/var/run/acpid.pid

case $1 in
start)
	$SSD --start --pidfile $PID --exec $PROG
	;;
stop)
	$SSD --stop --remove-pidfile --retry 10 --pidfile $PID
	;;
reload)
	$SSD --stop --signal HUP --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|reload|restart]"
	;;
esac

# End of file
